### ISSUE TITLE
where is the "ags" bar  in my "1200*1920" screen?

### ISSUE THREAD

**Issue by awarewen** [AhmedSaadi0/my-hyprland-config#12]
Is that dotfile config for 1920*1080?
![图片](https://github.com/user-attachments/assets/df521c87-3329-4594-80dd-92f0b9373ff3)

**Comment by awarewen** [comment]
![图片](https://github.com/user-attachments/assets/29407146-14b3-4d08-86b0-9866270f35bc)

**Comment by AhmedSaadi0** [comment]
Try 
```bash
killall ags
ags
```

and post log
