### ISSUE TITLE
KDE Plasma 6 Incompatibility 

### ISSUE THREAD

**Issue by Marin-Kitagawa** [AhmedSaadi0/my-hyprland-config#3]
KDE Material Colors You checks for the Plasma 5 version files. But I use KDE Plasma 6 already. So, there is a conflict and CMake fails. Your Hyprland config is extremely beautiful. This is the only problem I have. Is there a way to solve or bypass this?

**Comment by AhmedSaadi0** [comment]
Actually I haven't tried Plamsa-6 yet but try ignoring the KDE-Material-Colors package and continue installing, I think it will work but you will not be able to use dynamic themes 

if anything happens you can give me full log to see how to fix that

**Comment by Marin-Kitagawa** [comment]
Oh okay then. I will give it a try.

**Comment by AhmedSaadi0** [comment]
[kde-material-you-colors](https://github.com/luisbocanegra/kde-material-you-colors) Added support for plasma-6 so I think I should close this issue.
