### ISSUE TITLE
request some details

### ISSUE THREAD

**Issue by kaisolve** [AhmedSaadi0/my-hyprland-config#5]
hi i am trying to install t but i didn't found waybar or wallpapers so can you give me the full dots so i can install and setup the sys the right way?
رمضان كريم ;)

**Comment by AhmedSaadi0** [comment]
Hi, you don't need to have waybar installed, the bar and all the widgets are written in JavaScript using [AGS](https://github.com/Aylur/ags/wiki/). 
The wallpapers and all needed files are already there, you just need to install all required apps and copy the files to the right places then everything should work fine. If you face any issue give me full log.

رمضان كريم 😇

**Comment by AhmedSaadi0** [comment]
I think this issue should be closed, feel free to open it again if you face any other problems.

عيد سعيد وكل عام وانتم بخير 😇
