### ISSUE TITLE
Name of Folder icons

### ISSUE THREAD

**Issue by VehementHam** [AhmedSaadi0/my-hyprland-config#7]
Please detail the names of the icons and display links for their respective home pages.

**Comment by VehementHam** [comment]
https://store.kde.org/p/2037657/

**Comment by AhmedSaadi0** [comment]
All icons are available in the dot [here](https://github.com/AhmedSaadi0/my-hyprland-config/tree/main/config/icons). It's a good idea to add their names and the link for credibility. I'll make sure to include them as well. Thanks for the reminder.
