### ISSUE TITLE
Cant make it work on intel GPU

### ISSUE THREAD

**Issue by rakibulmuhajir** [AhmedSaadi0/my-hyprland-config#9]
i have 11th gen dell laptop with dual gpu. i want to run hyprland on intel. but your setup does not. followed all the directions on a fresh arch install

here is crash report

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Who tried dividing by zero?!

Hyprland received signal 6(ABRT)
Version: ea2501d4556f84d3de86a4ae2f4b22a474555b9f
Tag: v0.41.0

System info:
	System name: Linux
	Node name: archlinux
	Release: 6.6.33-1-lts
	Version: #1 SMP PREEMPT_DYNAMIC Thu, 13 Jun 2024 16:25:55 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-H GT1 [UHD Graphics] [8086:9a60] (rev 01) (prog-if 00 [VGA controller])

os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
Backtrace:
	# | Hyprland(_Z12getBacktracev+0x61) [0x5f1c459c4511]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x9d9) [0x5f1c4595b1a9]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x71) [0x5f1c458e8ab1]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /usr/lib/libc.so.6(+0x3cae0) [0x7f2323050ae0]
		??
		??:0
	#4 | /usr/lib/libc.so.6(+0x94e44) [0x7f23230a8e44]
		??
		??:0
	#5 | /usr/lib/libc.so.6(gsignal+0x20) [0x7f2323050a30]
		??
		??:0
	#6 | /usr/lib/libc.so.6(abort+0xdf) [0x7f23230384c3]
		??
		??:0
	#7 | /usr/lib/libstdc++.so.6(+0x97b0c) [0x7f2323297b0c]
		??
		??:0
	#8 | /usr/lib/libstdc++.so.6(+0xadf1a) [0x7f23232adf1a]
		??
		??:0
	#9 | /usr/lib/libstdc++.so.6(_ZSt10unexpectedv+0) [0x7f232329750a]
		??
		??:0
	#1 | /usr/lib/libstdc++.so.6(+0xae1d6) [0x7f23232ae1d6]
		??
		??:0
	#11 | Hyprland(+0xa5ab8) [0x5f1c45857ab8]
		??
		??:0
	#12 | Hyprland(_ZN11CCompositor10initServerEv+0x466) [0x5f1c458efcb6]
		CCompositor::initServer()
		??:?
	#13 | Hyprland(main+0x8d9) [0x5f1c458ace49]
		main
		??:?
	#14 | /usr/lib/libc.so.6(+0x25c88) [0x7f2323039c88]
		??
		??:0
	#15 | /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7f2323039d4c]
		??
		??:0
	#16 | Hyprland(_start+0x25) [0x5f1c458e5e75]
		_start
		??:?

Log tail:
[LOG] Runtime directory: /run/user/1000/hypr/ea2501d4556f84d3de86a4ae2f4b22a474555b9f_1718422275_1842805500
[LOG] Hyprland PID: 5600
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: archlinux
[LOG] Release: 6.6.33-1-lts
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Thu, 13 Jun 2024 16:25:55 +0000

[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-H GT1 [UHD Graphics] [8086:9a60] (rev 01) (prog-if 00 [VGA controller])

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: Alors on danse

[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 41.39µs. Estimated average calc time: 0.11µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.88µs. Estimated average calc time: 0.08µs.
[LOG] Using config: /home/evo/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Creating the CHyprError!
[LOG] Creating the LayoutManager!
[LOG] Creating the TokenManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.24µs. Estimated average calc time: 0.03µs.
[LOG] Using config: /home/evo/.config/hypr/hyprland.conf
[ERR] source= globbing error: found no match
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 21.62µs. Estimated average calc time: 0.09µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.15µs. Estimated average calc time: 0.07µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.14µs. Estimated average calc time: 0.09µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.16µs. Estimated average calc time: 0.04µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.08µs. Estimated average calc time: 0.03µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.04µs. Estimated average calc time: 0.07µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.05µs. Estimated average calc time: 0.07µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.15µs. Estimated average calc time: 0.08µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.02µs. Estimated average calc time: 0.05µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.07µs. Estimated average calc time: 0.06µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.10µs. Estimated average calc time: 0.07µs.
[LOG] Disabling stdout logs! Check the log for further logs.
[LOG] Creating the PointerManager!
[backend/backend.c:224] Cannot create X11 backend: disabled at compile-time
[CRITICAL] m_sWLRBackend was NULL! This usually means wlroots could not find a GPU or enountered some issues.
[CRITICAL] Critical error thrown: wlr_backend_autocreate() failed!

**Comment by AhmedSaadi0** [comment]
It appears that Hyprland is crashing on your system. you might want to Search for installation guides or troubleshooting tips specific to Hyprland on Intel TigerLake-H, or report this issue on the [official Hyprland](https://wiki.hyprland.org/Crashes-and-Bugs/) website or support forums for further assistance.
